### ISSUE TITLE
CamViewer method fails in Lucid

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/lucid#107]
The laser group recently reported that the cam_viewer method of our `PCDSAreaDetectorTyphos` class doesn't seem to work when opening the device from our LUCID homescreen. See the image below where the method button is disconnected. 

When using the device class from an Ipython session things seem to work fine. 

From LUCID:
![image](https://user-images.githubusercontent.com/29102919/189394274-7de9baf6-dc5a-4297-85ce-8a8db834134d.png)

From Ipython:
![image](https://user-images.githubusercontent.com/29102919/189394935-25f2c278-a950-4853-adeb-0287bea85978.png)

**Comment by slactjohnson** [comment]
Not totally sure where this issue belongs, but since things seem fine from python and Typhos this seems like a LUCID issue?

**Comment by klauer** [comment]
```
[2022-09-09 09:42:43,058] [ERROR   ] - Unable to make proper connection for <PyDMChannel (sig://las_lhn_bay1_cam_ff_cam_viewer)>
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pydm/widgets/channel.py", line 135, in connect
    pydm.data_plugins.establish_connection(self)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pydm/data_plugins/__init__.py", line 67, in establish_connection
    establish_connection_immediately(channel)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pydm/data_plugins/__init__.py", line 72, in establish_connection_immediately
    plugin.add_connection(channel)
AttributeError: 'NoneType' object has no attribute 'add_connection'
```

OK - so we need to reinstall typhos (not just `git pull`) because it uses the `sig://` plugin  which is defined by entrypoint

**Comment by klauer** [comment]
I reinstalled typhos in the development environment and successfully tested it locally. @slactjohnson, can you confirm that it works on the laser machines?

**Comment by klauer** [comment]
@ZLLentz resolved this with his write permissions. Closing.

**Comment by slactjohnson** [comment]
Thanks @ZLLentz @klauer ! Somehow I missed this last week. I confirmed it works for me as well.
