### ISSUE TITLE
Add excepthooks to ensure the launcher doesn't crash

### ISSUE THREAD

**Issue by klauer** [pcdshub/lucid#11]
`sys.excepthook`, `threading.excepthook`, ...

Could use `raise_to_user` to show exception, or just dump it in the console.

**Comment by klauer** [comment]
In light of stuff like #44, we should prioritize getting this in. Perhaps it even belongs in pcdsutils for reuse between our projects.

**Comment by hhslepicka** [comment]
Makes sense. I will add it in.
