### ISSUE TITLE
Force beamline to be all caps

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lucid#46]
After https://github.com/pcdshub/happi/issues/100, accept inputs like:
`lucid lfe`
And internally change `lfe` to `LFE`

Raj and I were stuck on this for a bit

**Comment by hhslepicka** [comment]
Should we do that at `lucid` or allow `happi` search to be case-insensitive?

**Comment by ZLLentz** [comment]
That's a good question... I'm not sure

**Comment by klauer** [comment]
👍 for case-insensitive search.
