### ISSUE TITLE
Runtime Error Connection Deleted

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lucid#56]
Sometimes we get this pop up in the control room:

RuntimeError: wrapped C/C++ object of type Connection has been deleted

Sometimes the screen crashes, sometimes it happily continues on

**Comment by ZLLentz** [comment]
In this particular instance, the pop up opened 24 times

**Comment by hhslepicka** [comment]
@ZLLentz can you track down some steps to reproduce it?
Is it happening while opening Lucid or after it is open for a while?

**Comment by ZLLentz** [comment]
This happens when it is open for a while. I assume someone is restarting an IOC of some kind? The user is not doing any additional input when these happen and there isn't any obvious change in the system.

**Comment by hhslepicka** [comment]
Interesting... i will try to debug that here.

**Comment by hhslepicka** [comment]
That was addressed with the latest fix of PyDM, also related to #73
