### ISSUE TITLE
New typhos suite will not show top-level device

### ISSUE THREAD

**Issue by klauer** [pcdshub/lucid#65]
Click:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5139267/81850781-4ef4c900-950d-11ea-8415-88f073452bdc.png">

Then get:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/5139267/81850750-48665180-950d-11ea-8793-36c1d50ee832.png">

I think this is preferable to the old behavior of showing the first device, in which case this is not an issue. Thoughts?

**Comment by hhslepicka** [comment]
Closed but here is my comment.
IMHO that is preferrable than showing only the first device. User should pick which one to display.
We already cover a lot of things such as:
- if only one device, display it
- options to open specific device
