### ISSUE TITLE
Using noMachine, The LFE screen partially loads.

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lucid#66]
The screen partially loads when I go through psnxserv then psdev then xpp-control.

![image](https://user-images.githubusercontent.com/42284230/83779601-08444b80-a641-11ea-8dff-c6a5fb17346a.png)

**Comment by hhslepicka** [comment]
@slacAdpai can you use fastx3?

**Comment by slacAdpai** [comment]
Yes, I can use fastx. I was trying out nomachine because fastx has a 4 second lag between pressing a button on a gui and the plc seeing the input.

**Comment by hhslepicka** [comment]
@slacAdpai did you try the recommendation provided by Zach? Are you still seeing issues?

**Comment by ZLLentz** [comment]
Seems like we managed to change the green to black by changing the rendering settings :shrug: but the issue persists...

**Comment by ZLLentz** [comment]
Hang on, there's something here- we're walking through this together on zoom

**Comment by slacAdpai** [comment]
Go to display, change settings, and check all the 5 options on the bottom. Then restart your entire session and the lfe screens and iocmanager screens will show up properly.
![image](https://user-images.githubusercontent.com/42284230/87204779-8cca5f80-c2ba-11ea-9fd0-e5b5da4aa9e4.png)
