### ISSUE TITLE
HXR vacuum screen crashes and there is a C code error and this is the printout

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lucid#73]
```
File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/base.py", line 703, in connectionStateChanged
    self.connection_changed(connected)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/base.py", line 568, in connection_changed
    self.alarmSeverityChanged(self.ALARM_NONE)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/base.py", line 732, in alarmSeverityChanged
    self.alarm_severity_changed(new_alarm_severity)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/base.py", line 623, in alarm_severity_changed
    refresh_style(self)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/base.py", line 90, in refresh_style
    child_widget.style().unpolish(child_widget)
```

**Comment by hhslepicka** [comment]
@slacAdpai is this happening at all times? Do you have the rest of the error message?

**Comment by slacAdpai** [comment]
Bill schlotter is having this issue as well. It is crashing while we are doing checkouts.

**Comment by hhslepicka** [comment]
Can you jump into a zoom call to demo it?

**Comment by slacAdpai** [comment]
I'll try again

**Comment by slacAdpai** [comment]
https://stanford.zoom.us/j/5939260898?pwd=SmdraE1jVkhheUhTMUVqWnd1MU9adz09

**Comment by hhslepicka** [comment]
I removed the link from here.

**Comment by jsheppard95** [comment]
So I was just about to make a new issue for this, as I just had something similar happen:

I had the `lfe` screen up looking at the mirrors, along with a `telnet` session open to my IOC but with my PLC still in config mode. I then accidentally rebooted my IOC before setting my PLC into run mode. This caused everything to freeze on `xpp-daq`, even though I was just using this machine to ssh to `lfe-console` (this machine was where I called the screen and had a `telnet` session to the IOC open). I then connected to `lfe-console` from my laptop to kill the process that was running the screen (as I expected this caused the C code error), and this caused `xpp-daq` to completely shut down. I rebooted it though and it seemed to come back in an okay state.

So definitely user error with rebooting the IOC before the PLC was running, but I wouldn't expect this to take down the whole machine.

**Comment by hhslepicka** [comment]
@jsheppard95 thank you for reporting back. I will add a new version of PyDM with protections against those C errors that Allen reported. Do you by any chance have the output of your error? Was it the same?

Thanks you!

**Comment by jsheppard95** [comment]
Unfortunately I don't. I forgot to take pictures at the time. There was also a graphical error message that popped up that said something along the lines of "An underlying C/C++ object has been deleted", but I also forgot to take a picture of this, sorry about that!

**Comment by hhslepicka** [comment]
No problem at all... I will add some more protections to PyDM and get back to you for some tests.
Thanks!

**Comment by hhslepicka** [comment]
@jsheppard95 @slacAdpai I just deployed the latest from PyDM at dev-conda. Would you please give it a try and let me know if it is more stable?

**Comment by jsheppard95** [comment]
Sure can do, should I actually just replicate my process and reboot an IOC with the PLC in config mode to see what happens?

**Comment by hhslepicka** [comment]
@jsheppard95 that would be the best test if you could. Please remember to close your screens before doing the test to make sure you load the latest PyDM at the dev-conda environment.

**Comment by jsheppard95** [comment]
@hhslepicka Yes can do! I can do so for MR1K2 which is still in more of a development state anyway. I think I'll wait until this afternoon when there is less traffic in the XPP control room, but I'll give another update after with what I find.

Thanks for the updates!

**Comment by hhslepicka** [comment]
@jsheppard95 no need to test it... I was able to finally reproduce the issue that you saw here locally. I will keep you posted. Please abort the test for now.

**Comment by jsheppard95** [comment]
@hhslepicka Oh that's great to hear, I was a bit worried about taking down the control room machine again.

Thanks again for working on this!

**Comment by hhslepicka** [comment]
I was able to track the issue down to PyEPICS... I am working on a temporary fix at the PyDM side while we don't fix it upstream. More news soon.

**Comment by hhslepicka** [comment]
@jsheppard95 the fix was deployed... would you mind to test it and get back to me later? No rush!

**Comment by jsheppard95** [comment]
@hhslepicka That seems to have fixed it! Just replicated the process with MR1K2 where again I had the screen open, the PLC in config mode, and attempted an IOC reboot, and now it seems very stable. Went through a few reboots and both the screen and xpp-daq are perfectly responsive. I just an angry telnet session as expected.

Thanks for helping with this!

**Comment by hhslepicka** [comment]
Awesome! Thanks @jsheppard95 ! I will close this PR based on your tests. If you see it again please feel free to reopen it.

**Comment by jsheppard95** [comment]
Sounds good, I'll keep an eye out and let you know if I run into more issues, and I'll make sure to take pictures - good practice in any sort of crash whether it be in a car or software!
